---
abstract: 'Tool to fetch record from National library of the Czech Republic to MARC file.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-NKC2MARC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Encode: 0
  English: 0
  Error::Pure: 0
  Getopt::Std: 0
  IO::Barf: 0
  MARC::Record: 0
  ZOOM: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-NKC2MARC/issues
  homepage: https://github.com/michal-josef-spacek/App-NKC2MARC
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-NKC2MARC
version: '0.01'
